### ISSUE TITLE
Todo list for redesign

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman-webextension#61]
To do list for the [redesign](https://github.com/nextcloud/passman-webextension/tree/redesign) branch.   
- [x] Add extension version to settings page
- [x] Add number of credentials in database in menu footer
- [x] Add toasts for showing errors
- [x] Edit custom fields
- [x] Add material setup 
- [x] Test on Chrome
- [x] Test on Firefox

**Comment by brantje** [comment]
Is live!
